### ISSUE TITLE
Windows Help

### ISSUE THREAD

**Issue by BAKova** [Kgray44/Talking-High-Temperature-Sensor#1]
Purchased the parts per your list for building the Talking-High-Temperature-Sensor. Everything looks correct except for the  DFR0282 Beetle, the  actual part does not have the connections shown on your schematic. Specifically, the SDA and SCL connnections are missing. Can you assist?

**Comment by Kgray44** [comment]
Hi @BAKova 

Glad you're following my tutorial!  

Here is the schematic as pictured in my tutorial:
![schematic_dfrobot_talking_wood_stove_temperature_sensor_2023-02-17_Wwqej2xn0N](https://github.com/Kgray44/Talking-High-Temperature-Sensor/assets/64373011/547bf0da-1c96-44bd-b5e8-89326f9e1751)

The Beetle is pictured in the middle.  The I2C lines come off of the top and the bottom of it as pictured.  You just need to make sure the SCL pin of the beetle is wired to the SCL pin on the temperature sensor module and the display, and the same done with the SDA.

<img width="295" alt="Screenshot 2024-01-16 at 5 54 24 PM" src="https://github.com/Kgray44/Talking-High-Temperature-Sensor/assets/64373011/3b7b975f-fac4-48af-95c2-0e46b5cadbe4">

Here is the image of the bottom of the Beetle; the I2C connections are the soldering pads placed on the bottom of the board.

Do you have any more questions?  I hope this helped!

**Comment by BAKova** [comment]
Thanks, that clears things up, but I'm a little concerned about heating those pads when soldering, any suggestions?

**Comment by Kgray44** [comment]
Hi @BAKova 

There's no worries with heating those pads during soldering.  As a general rule of thumb, when I am soldering at 450 degrees, I make sure to heat the pads for 5 seconds or less, just to make sure I don't heat anything too much.

Good luck soldering!

**Comment by BAKova** [comment]
Ok, I have everything wired and ready to go but I can't locate the disk utility to format etc. can you send me a link

**Comment by BAKova** [comment]
I Belive I found it'

**Comment by BAKova** [comment]
Recorded my messages, downloaded your program and made my changes, saved the file to my hard drive then tried to upload it to the voice recorder but I'm not successful, is there a step I'm missing here, get an error that the file path dosen't exist

**Comment by Kgray44** [comment]
Hi @BAKova 

Please check the updated tutorial.

You will need to move the correct voice files to the Voice Recorder Module (if you haven't recorded your voice); please check [the section linked](https://www.hackster.io/k-gray/talking-wood-pellet-stove-high-temperature-sensor-75f370#toc-saving-audio-files-to-the-voice-recorder-module-6).

Then you can upload the .ino code file to the Beetle in the Arduino IDE via a Micro-USB cable.

**Comment by BAKova** [comment]
I did the voice recordings directly into the voice recorder, no issues, and they are named properly. The issues I'm having now are as follows:
1.) The Arduino Uno does not show a port in the setup
2.) When I run verify/compile it can't find the library eventhough it is in the same directory as the other libraries, which load without issue (C:\Users\789ba\arduino\libraies.  I Don't know why it's looking here
ERROR MESSAGE
C:\Users\789ba\Documents\Home\Projects\Stove Alarm\sketch_jan18a\sketch_jan18a.ino:4:10: fatal error: DFRobot_MAX31855.h: No such file or directory
 #include <DFRobot_MAX31855.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1
Compilation error: DFRobot_MAX31855.h: No such file or directory

3.) Can't upload without the port designation.
4.) Do I need to have a separate 5DC powering the circuit besides the USB during these operations?
5.) I formated the board to FAT file system, using windows 10 which took less than a minute, could this be part of my problems?

**Comment by Kgray44** [comment]
Hi @BAKova 

I will answer your questions one by one:

1.) You are using an Arduino Uno?  Or are you using the suggested DFRobot Beetle?  To select the USB port, in the Arduino IDE you need to go to _Tools_  / _Port_.
<img width="1425" alt="Screenshot 2024-01-19 at 8 58 43 PM" src="https://github.com/Kgray44/Talking-High-Temperature-Sensor/assets/64373011/486b8735-cd9e-482b-943a-f4b17c36f95c">

Make sure to select your correct board first in _Tools_ / _Boards_ (Arduino Leonardo if you are using the Beetle).
<img width="1419" alt="Screenshot 2024-01-19 at 9 03 33 PM" src="https://github.com/Kgray44/Talking-High-Temperature-Sensor/assets/64373011/1268837f-edce-4d75-a37b-c01008a61d37">

2.) Are you positive you downloaded and installed that library?  Once downloaded from [here](https://github.com/DFRobot/DFRobot_MAX31855), you will need to add it to C:\Users\789ba\arduino\libraries.

Where is your sketch file located?

3.) Refer to #1

4.) No, a separate 5VDC power supply is not needed at all, although it can be used instead of powering it via USB.

5.) I am a bit confused here 🤔.  What board did you format?  The Voice Recorder Module?  To quote my tutorial:

> ![image](https://github.com/Kgray44/Talking-High-Temperature-Sensor/assets/64373011/7f48e067-ade8-4474-be8b-b5fc8349c29e)
> Pick a suitable name (I picked "DFR VOICE"), select the format as MS-DOS (FAT), and select the Scheme as GUID Partition Map. Now, click Erase!

So FAT should be fine here.  Taking less than a minute doesn't seem right though, as mine took over an hour since the storage on the module has a very low data rate.  This wouldn't cause any programming problems with the Beetle though; the only thing that would happen is nothing would play when you run the code.

Hope this helps!

**Comment by BAKova** [comment]
I switched to the Arduino Leonardo as suggested, I downloaded the wrong library (oops) now that the correct one is in I'm able to compile and verify. Sketch File is located in C:\Users\789ba\arduino\ 
However, I still can't get the port option to become active.

**Comment by BAKova** [comment]
![port error](https://github.com/Kgray44/Talking-High-Temperature-Sensor/assets/156849155/69898cb8-279d-420c-8423-be8f6e877cdc)
